### ISSUE TITLE
Compatibility with Laravel projects

### ISSUE THREAD

**Issue by Pablo1107** [haginaga/vim-compiler-phpunit#1]
Hi! I'm trying to get vim-test + neomake setup working. With your compiler (and with afternoon aswell) the errorformat always grabs the first file of the phpunit output.

This is the output of the example Laravel test.

```
PHPUnit 6.5.8 by Sebastian Bergmann and contributors.                                                                                 

F.                                                                  2 / 2 (100%)

Time: 96 ms, Memory: 14.00 MB

There was 1 failure:

1) Tests\Feature\ExampleTest::testBasicTest
Expected status code 404 but received 200.
Failed asserting that false is true.

/home/pablo/code/<project-name>/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/home/pablo/code/<project-name>/tests/Feature/ExampleTest.php:19

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```
And this is the parsed by dispatch-vim output:

```
|| PHPUnit 6.5.8 by Sebastian Bergmann and contributors.
|| 
|| F                                                                   1 / 1 (100%)
|| 
|| Time: 89 ms, Memory: 14.00MB
|| 
|| There was 1 failure:
|| 
vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php|78 error   1|  Expected status code 404 but received 200. Failed asserting that false is true.
|| /home/pablo/code/<project-name>/tests/Feature/ExampleTest.php:19
|| 
|| FAILURES!
|| Tests: 1, Assertions: 1, Failures: 1.
```

I want someway in which the errorformat ignore the first file and points the error the ExampleTest.php.

I tried adding a %> after %Z in the CompilerSet line, and this give me the choice to select all the output files in the quicklist, but with no message error.

`CompilerSet errorformat=%E%n)\ %.%#,%Z,%>%f:%l,%C%m,%C,%-G%.%#`

**Comment by Slamdunk** [comment]
Hi, @haginaga seems inactive till a year ago.

I've updated the `errorformat` to bare `%f:%l` in my fork https://github.com/Slamdunk/vim-compiler-phpunit so every file in the stack trace becomes "jumpable":

![image](https://user-images.githubusercontent.com/152236/122342920-70608980-cf45-11eb-94b0-af1cf16b8169.png)
